export const GET_COMMENTS_BY_USER_ID_REQUEST = 'GET_COMMENTS_BY_USER_ID_REQUEST'
export const GET_COMMENTS_BY_USER_ID_SUCCESS = 'GET_COMMENTS_BY_USER_ID_SUCCESS'
export const GET_COMMENTS_BY_USER_ID_FAIL = 'GET_COMMENTS_BY_USER_ID_FAIL'

export const GET_COMMENTS_BY_GROUP_ID_REQUEST = 'GET_COMMENTS_BY_GROUP_ID_REQUEST'
export const GET_COMMENTS_BY_GROUP_ID_SUCCESS = 'GET_COMMENTS_BY_GROUP_ID_SUCCESS'
export const GET_COMMENTS_BY_GROUP_ID_FAIL = 'GET_COMMENTS_BY_GROUP_ID_FAIL'

export const GROUPING_COMMENTS_REQUEST = 'GROUP_COMMENTS_REQUEST'
export const GROUPING_COMMENTS_SUCCESS = 'GROUP_COMMENTS_SUCCESS'
export const GROUPING_COMMENTS_FAIL = 'GROUP_COMMENTS_FAIL'

export const GET_COMMENTS_IN_GROUP_DESC_REQUEST = 'GET_COMMENTS_IN_GROUP_DESC_REQUEST'
export const GET_COMMENTS_IN_GROUP_DESC_SUCCESS = 'GET_COMMENTS_IN_GROUP_DESC_SUCCESS'
export const GET_COMMENTS_IN_GROUP_DESC_FAIL = 'GET_COMMENTS_IN_GROUP_DESC_FAIL'

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL'
export const POST_COMMENT_RESET = 'POST_COMMENT_RESET'


export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET'

export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST'
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS'
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL'
export const UPDATE_COMMENT_RESET = 'UPDATE_COMMENT_RESET'

export const GET_COMMENT_LIKES_REQUEST = 'GET_COMMENT_LIKES_REQUEST'
export const GET_COMMENT_LIKES_SUCCESS = 'GET_COMMENT_LIKES_SUCCESS'
export const GET_COMMENT_LIKES_FAIL = 'GET_COMMENT_LIKES_FAIL'

