export const GET_ALL_GROUP_REQUEST = 'GET_ALL_GROUP_REQUEST'
export const GET_ALL_GROUP_SUCCESS = 'GET_ALL_GROUP_SUCCESS'
export const GET_ALL_GROUP_FAIL = 'GET_ALL_GROUP_FAIL'


export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST'
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS'
export const ADD_GROUP_FAIL = 'ADD_GROUP_FAIL'
export const ADD_GROUP_RESET = 'ADD_GROUP_RESET'

export const GET_GROUP_USERS_REQUEST = 'GET_GROUP_USERS_REQUEST'
export const GET_GROUP_USERS_SUCCESS = 'GET_GROUP_USERS_SUCCESS'
export const GET_GROUP_USERS_FAIL = 'GET_GROUP_USERS_FAIL'

export const GET_GROUP_DETAILS_REQUEST = 'GET_GROUP_DETAILS_REQUEST'
export const GET_GROUP_DETAILS_SUCCESS = 'GET_GROUP_DETAILS_SUCCESS'
export const GET_GROUP_DETAILS_FAIL = 'GET_GROUP_DETAILS_FAIL'

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL'
export const DELETE_GROUP_RESET = 'DELETE_GROUP_RESET'

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'
export const UPDATE_GROUP_RESET = 'UPDATE_GROUP_RESET'

export const GET_MY_GROUPS_REQUEST = 'GET_MY_GROUPS_REQUEST'
export const GET_MY_GROUPS_SUCCESS = 'GET_MY_GROUPS_SUCCESS'
export const GET_MY_GROUPS_FAIL = 'GET_MY_GROUPS_FAIL'